CREATE TABLE games (
  game_id TEXT PRIMARY KEY,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER NOT NULL AUTOINCREMENT REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE moves (
  move_id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id TEXT NOT NULL REFERENCES games(game_id) ON DELETE CASCADE,
  ply INTEGER NOT NULL,
  uci TEXT NOT NULL
);

CREATE TABLE users (
  user_id INTEGER UNIQUE PRIMARY KEY NOT NULL AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE PRIMARY KEY
  2fa BOOLEAN NOT NULL
);
